### ISSUE TITLE
软件找不到实时字幕

### ISSUE THREAD

**Issue by dadaewqq** [M-T-Arden/MTtranslator#1]
无论怎么样操作 都显示如下

![image](https://github.com/user-attachments/assets/3300fa8a-7762-4873-aee1-66ddfc1412ac)

**Comment by M-T-Arden** [comment]
已收到反馈，是打开实时字幕重启，再重启本软件也没用吗？如果是的话，你把系统语言切换到英语试试，可能是因为识别UI识别的是英文名。感谢反馈，我之后根据这个再做一下调整。

**Comment by dadaewqq** [comment]
是的 怎么调整启动顺序都没用  有空我切一下语言试试🤔
（系统版本24h2）

**Comment by M-T-Arden** [comment]
已经优化完毕，系统语言是中文也可以使用了。
